% This requires:
% - calculated LUT files generated by Chris, and its directory
% - header info files (GE)
% - excel sheet called 'subjectNames' saved in each sites folder (look for
%   variable 'T')
% - balsa surface atlas
% - You can IGNORE MNIdir and MNISavDir, those are for new LUT only. 

% Adjust the appropriate directory lines in for the above changes:
% Siemens_SubList_makeCalcT1() -> lines 1:60
% GE_SubList_makeCalcT1() -> lines 1:60


%%%%%%%%%%%%%%% Note! 
% Having all volumes loaded is expensive in memory. 
% To deal with this, start with volumes, calculate ROI values, then clear
% the volumes. THEN bring in the surfaces. 

%% Load necessary code:
if isunix
    filePath  = '/media/chris/SSD/';
elseif ispc
    % Code to run on Windows platform
    filePath  = 'E:\';
else
    disp('Platform not supported')
end

%addpath(genpath('/media/chris/DataHDD/user/code/matlab/niak-master' ))  % loading volumes
addpath(genpath( [filePath,'Research/Bipolar/Longitudinal_ICM_BD/BipolarMatlab/gifti-1.6'] ));
addpath(genpath( [filePath,'[filePath,Research/Bipolar/Longitudinal_ICM_BD/BipolarMatlab/ChrisR'] ));
addpath(genpath( [filePath,'Research/Bipolar/Longitudinal_ICM_BD/BipolarMatlab/cifti-matlab-master'] ));
addpath(genpath( [filePath,'Research/Bipolar/Longitudinal_ICM_BD/BipolarMatlab/surfstat'] ));
addpath(genpath( [filePath,'Research/Code/NeuroImagingMatlab/NeuroImagingMatlab'] )) % for limitHandler

%% File locations
DD = [filePath, 'Research/Bipolar/Longitudinal_ICM_BD/'];
DATA_DIR = strcat(DD,'Longitudinal_ICM_BD_in_HDD/data/'); % Linux
% ATLAS_DIR = strcat(DD, 'Longitudinal_ICM_BD_in_HDD/Atlas/Balsa_Surfaces/');
SavDir = strcat( DD,'BipolarMatlab/ChrisR/EmpiricalSolver/data/');

ATLAS_DIR = 'F:\user\Research\Longitudinal_ICM_BD/Atlas/Balsa_Surfaces/';



%% Surfaces

[B1_1, T1_1, Subnames_1, missingData_1] = GE_SubList_makeCalcT1(1, []); % McMaster
[B1_2, T1_2, Subnames_2, missingData_2] = GE_SubList_makeCalcT1(2, []); % Dal
[B1_3, T1_3, Subnames_3, missingData_3] = GE_SubList_makeCalcT1(3, []); % Calgary

[B1_4, T1_4, Subnames_4, missingData_4] = Siemens_SubList_makeCalcT1(4, []); % Queens
[B1_5, T1_5, Subnames_5, missingData_5] = Siemens_SubList_makeCalcT1(5, []); % UHN

temp2 = T1_5(:,:,1);
temp3 = T1_4(:,:,1);

%% For data reduction/visulation, lets average over ROIs
% Load ROIs
S_L=gifti(strcat(ATLAS_DIR, 'Q1-Q6_RelatedParcellation210.L.inflated_MSMAll_2_d41_WRN_DeDrift.32k_fs_LR.surf.gii'));
S_R=gifti(strcat(ATLAS_DIR, 'Q1-Q6_RelatedParcellation210.R.inflated_MSMAll_2_d41_WRN_DeDrift.32k_fs_LR.surf.gii'));

surface_L.coord = double(S_L.vertices');       % make sure this is 3*numverticies, if not transpose
surface_L.tri = double(S_L.faces);    

surface_R.coord = double(S_R.vertices');       % make sure this is 3*numverticies, if not transpose
surface_R.tri = double(S_R.faces);   

% load ROI values
% try using cifti load code...
l_L2 = cifti_read(strcat(ATLAS_DIR, 'Q1-Q6_RelatedParcellation210.L.CorticalAreas_dil_Colors.32k_fs_LR.dlabel.nii'));
label_L = CR_CIFTIcdata(l_L2.cdata, 32492, l_L2.diminfo{1,1}.models{1,1}.vertlist);

l_R2 = cifti_read(strcat(ATLAS_DIR, 'Q1-Q6_RelatedParcellation210.R.CorticalAreas_dil_Colors.32k_fs_LR.dlabel.nii'));
label_R = CR_CIFTIcdata(l_R2.cdata, 32492, l_R2.diminfo{1,1}.models{1,1}.vertlist);

% View label Surface
figure;
SurfStatViewData_HCP(label_L, surface_L, label_R, surface_R,'Labels',[0.2 0.2 0.2]); %inputs: data, surface, title, background colour
SurfStatColLim([0 180]);
set(gcf,'Position',[100 100 800 600])


%% Remove rows with Zeros 

temp2 = T1_5(:,:,1);
temp3 = T1_4(:,:,1);
temp4 = B1_4(:,:,1);

temp3 = T1_3( max(T1_3(:,:,1),[],2)>0, :,1) ;

%% View 

val_L = nanmean( T1_1(max(T1_1(:,:,1),[],2)>0, :,1) , 1); val_R = nanmean( T1_1(max(T1_1(:,:,1),[],2)>0, :,2) , 1);

figure;
SurfStatViewData_HCP(val_L, surface_L, val_R, surface_R,'McMaster',[0 0 0]) %inputs: data, surface, title, background colour
SurfStatColLim([950 1500]); %saveas(gcf,strcat(SavDir,SITE,'-SurfaceMap_T1uncorrected.png'))  


val_L = nanmean( T1_2(max(T1_2(:,:,1),[],2)>0, :,1) , 1); val_R = nanmean( T1_2(max(T1_2(:,:,1),[],2)>0, :,2) , 1);

figure;
SurfStatViewData_HCP(val_L, surface_L, val_R, surface_R,'Dal',[0 0 0]) %inputs: data, surface, title, background colour
SurfStatColLim([950 1500]); %saveas(gcf,strcat(SavDir,SITE,'-SurfaceMap_T1uncorrected.png'))  


val_L = nanmean( T1_3(max(T1_3(:,:,1),[],2)>0, :,1) , 1); val_R = nanmean( T1_3(max(T1_3(:,:,1),[],2)>0, :,2) , 1);

figure;
SurfStatViewData_HCP(val_L, surface_L, val_R, surface_R,'Calgary',[0 0 0]) %inputs: data, surface, title, background colour
SurfStatColLim([950 1500]); %saveas(gcf,strcat(SavDir,SITE,'-SurfaceMap_T1uncorrected.png'))  


val_L = nanmean( T1_4(max(T1_4(:,:,1),[],2)>0, :,1) , 1); val_R = nanmean( T1_4(max(T1_4(:,:,1),[],2)>0, :,2) , 1);

figure;
SurfStatViewData_HCP(val_L, surface_L, val_R, surface_R,'Queens',[0 0 0]) %inputs: data, surface, title, background colour
SurfStatColLim([950 1500]); %saveas(gcf,strcat(SavDir,SITE,'-SurfaceMap_T1uncorrected.png'))  


val_L = nanmean( T1_5(max(T1_5(:,:,1),[],2)>0, :,1) , 1); val_R = nanmean( T1_5(max(T1_5(:,:,1),[],2)>0, :,2) , 1);

figure;
SurfStatViewData_HCP(val_L, surface_L, val_R, surface_R,'UHN',[0 0 0]) %inputs: data, surface, title, background colour
SurfStatColLim([950 1500]); %saveas(gcf,strcat(SavDir,SITE,'-SurfaceMap_T1uncorrected.png'))  








% val_L = nanmean( B1_4(max(B1_4(:,:,1),[],2)>0, :,1) , 1); val_R = nanmean( B1_4(max(B1_4(:,:,1),[],2)>0, :,2) , 1);
% 
% figure;
% SurfStatViewData_HCP(val_L, surface_L, val_R, surface_R,'Queens',[0 0 0]) %inputs: data, surface, title, background colour
% SurfStatColLim([0.8 1.3]); %saveas(gcf,strcat(SavDir,SITE,'-SurfaceMap_T1uncorrected.png'))  










figure;
SurfStatViewData_HCP( (1./(val_L))*1000 , surface_L, (1./(val_R))*1000, surface_R,'R_1 (1/s)- uncorr',[0 0 0]) %inputs: data, surface, title, background colour
SurfStatColLim([1/1.4 1/0.95]);
saveas(gcf,strcat(SavDir,SITE,'-SurfaceMap_R1uncorrected.png'))  

val_L = nanmean( B1_mac(:,:,1) , 1);
val_R = nanmean( B1_mac(:,:,2) , 1);

figure;
SurfStatViewData_HCP(val_L, surface_L, val_R, surface_R,'B_1',[0 0 0]) %inputs: data, surface, title, background colour
SurfStatColLim([0.9 1.3]);
%saveas(gcf,strcat(SavDir,SITE,'-SurfaceMap_B1.png'))  









%% OLD CODE 

% % % 
% % % %% Load Volumes without B1 correction
% % % tic
% % %  [B1_mac_vol, T1_mac_vol, size_vol] = CR_Pull_GE_R1_matrixNoGains_funcVolumes(1);
% % % toc
% % % 
% % % % because of RAM requirements, split this into a different function. 
% % % [wm_parc, size_vol2] = CR_Pull_labelVolumes(1);
% % % 
% % % 
% % % %% Save for future use:
% % % save(strcat(SavDir,'B1_mac_vol.mat'),'B1_mac_vol', '-v7.3')    
% % % save(strcat(SavDir,'T1_mac_vol.mat'),'T1_mac_vol', '-v7.3')    
% % % save(strcat(SavDir,'wm_parc_mac.mat'),'wm_parc', '-v7.3')   
% % % save(strcat(SavDir,'size_vol_mac.mat'),'size_vol')   
% % % 
% % % 
% % % %% Use wm_parc to pull some ROIs for asymmetry:
% % % % ROIs from: https://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/AnatomicalROI/FreeSurferColorLUT
% % % 
% % % leftROIs = [9:12, 1002:1034, 3002:3034  ];
% % % rightROIs = [48:51, 2002:2034, 4002:4034  ];
% % % 
% % % B1_asym_mac_vol = zeros(length(leftROIs), size(T1_mac_vol,1)); % ROIs by subject
% % % T1_asym_mac_vol = zeros(length(leftROIs), size(T1_mac_vol,1)); % ROIs by subject
% % % 
% % % for i = 1:length(leftROIs) % for each ROI
% % %     
% % %     for j = 1:size(T1_mac_vol,1) % for each subject, need to separate because volumes will be different sizes
% % % 
% % %         
% % %         labels = wm_parc(j,:);
% % %         maskL = zeros(size(labels));
% % %         maskR = zeros(size(labels));
% % %         maskL(labels == leftROIs(i)) = 1;
% % %         maskR(labels == rightROIs(i)) = 1;
% % %         
% % %         B1_left = B1_mac_vol(j,:); B1_left(maskL <1) = []; B1_left = mean(B1_left,'omitnan');
% % %         B1_right = B1_mac_vol(j,:); B1_right(maskR <1) = []; B1_right = mean(B1_right,'omitnan');
% % %         
% % %         T1_left = T1_mac_vol(j,:); T1_left(maskL <1) = []; T1_left = mean(T1_left,'omitnan');
% % %         T1_right = T1_mac_vol(j,:); T1_right(maskR <1) = []; T1_right = mean(T1_right,'omitnan');
% % %         
% % % 
% % %         B1_asym_mac_vol(i,j) = (B1_left- B1_right ) ./ B1_left;
% % %         T1_asym_mac_vol(i,j) = (T1_left - T1_right ) ./ T1_left;
% % %     end
% % %     i % print for progress...
% % % end
% % % 
% % % save(strcat(SavDir,'B1_asym_mac_vol.mat'),'B1_asym_mac_vol')   
% % % save(strcat(SavDir,'T1_asym_mac_vol.mat'),'T1_asym_mac_vol')   
% % % 
% % % % free the memory!
% % % clear wm_parc B1_mac_vol T1_mac_vol
% % % 
% % % % Visual Check:
% % % % q = 1:length(B1_left);
% % % % temp = zeros( size_vol);
% % % % temp(q) = maskL;
% % % % 
% % % % temp1 = zeros( size_vol);
% % % % temp1(q) = maskR;
% % % 
% % % % temp2 = zeros( size_vol);
% % % % temp2(q) = T1_mac_vol(j,:);
% % % % 
% % % % figure; imshow3Dfullseg(temp2   , [0 2250], temp)
% % % % figure; imshow3Dfullseg(temp2   , [0 2250], temp1)
% % % 
% % % %% Now we values for a bunch of ROIs and Subjects
% % % 
% % % % Pool them all. 
% % % 
% % % x_Plot_B1 = B1_asym_mac_vol(:);
% % % y_Plot_R1 = T1_asym_mac_vol(:);
% % % 
% % % y_Plot_R1( isnan(x_Plot_B1) ) = []; x_Plot_B1( isnan(x_Plot_B1) ) = [];
% % % x_Plot_B1( isnan(y_Plot_R1) ) = []; y_Plot_R1( isnan(y_Plot_R1) ) = [];
% % % 
% % % 
% % % y_Plot_R1( isinf(x_Plot_B1) ) = [];
% % % x_Plot_B1( isinf(x_Plot_B1) ) = [];
% % % 
% % % y_Plot_R1( x_Plot_B1 ==0 ) = [];
% % % x_Plot_B1( x_Plot_B1 ==0 ) = [];
% % % 
% % % x_Plot_B1( y_Plot_R1 >0.2 ) = [];
% % % y_Plot_R1( y_Plot_R1 >0.2) = [];
% % % 
% % % % do a visual check first: cftool
% % % figure;
% % % heatscatter(x_Plot_B1, y_Plot_R1)
% % % 

%%%%%%%%%%%%%%% 
%% Surfaces
location = 1;

if location == 1
    SITE = 'Mac';
elseif location ==2
    SITE = 'Dal';
end

% Start by loading B1 and R1 values. Generate R1's through lookup table WITHOUT B1 correction. 
[B1_mac, T1_mac] = CR_Pull_GE_R1_matrixNoGains_func( location, 'noB1corr' );
% [B1_dal, T1_dal]     = CR_Pull_GE_R1_matrixNoGains_func( 2 );
% [B1_cal, T1_cal]      = CR_Pull_GE_R1_matrixNoGains_func( 3 );

[~, T1_mac2] = CR_Pull_GE_R1_matrixNoGains_func( location, [] );



%% For data reduction/visulation, lets average over ROIs
% Load ROIs
S_L=gifti(strcat(ATLAS_DIR, 'Q1-Q6_RelatedParcellation210.L.inflated_MSMAll_2_d41_WRN_DeDrift.32k_fs_LR.surf.gii'));
S_R=gifti(strcat(ATLAS_DIR, 'Q1-Q6_RelatedParcellation210.R.inflated_MSMAll_2_d41_WRN_DeDrift.32k_fs_LR.surf.gii'));

surface_L.coord = double(S_L.vertices');       % make sure this is 3*numverticies, if not transpose
surface_L.tri = double(S_L.faces);    

surface_R.coord = double(S_R.vertices');       % make sure this is 3*numverticies, if not transpose
surface_R.tri = double(S_R.faces);   

% load ROI values
% try using cifti load code...
l_L2 = cifti_read(strcat(ATLAS_DIR, 'Q1-Q6_RelatedParcellation210.L.CorticalAreas_dil_Colors.32k_fs_LR.dlabel.nii'));
label_L = CR_CIFTIcdata(l_L2.cdata, 32492, l_L2.diminfo{1,1}.models{1,1}.vertlist);

l_R2 = cifti_read(strcat(ATLAS_DIR, 'Q1-Q6_RelatedParcellation210.R.CorticalAreas_dil_Colors.32k_fs_LR.dlabel.nii'));
label_R = CR_CIFTIcdata(l_R2.cdata, 32492, l_R2.diminfo{1,1}.models{1,1}.vertlist);

% View label Surface
figure;
SurfStatViewData_HCP(label_L, surface_L, label_R, surface_R,'Labels',[0.2 0.2 0.2]); %inputs: data, surface, title, background colour
SurfStatColLim([0 180]);
set(gcf,'Position',[900 900 1600 1200])


%% Smooth Surfaces:
% 
% smoothKernel = 7;
% 
% for i = 1:size(T1_mac,1)
%     T1_mac(i,:,1) = SurfStatSmooth( T1_mac(i,:,1), surface_L, smoothKernel );
%     T1_mac(i,:,2) = SurfStatSmooth( T1_mac(i,:,2), surface_R, smoothKernel );
%     B1_mac(i,:,1) = SurfStatSmooth( B1_mac(i,:,1), surface_L, smoothKernel );
%     B1_mac(i,:,2) = SurfStatSmooth( B1_mac(i,:,2), surface_R, smoothKernel );
%     T1_mac2(i,:,1) = SurfStatSmooth( T1_mac(i,:,1), surface_L, smoothKernel );
%     T1_mac2(i,:,2) = SurfStatSmooth( T1_mac(i,:,2), surface_R, smoothKernel );
% end

% View an average surface for both

val_L = nanmean( T1_mac(:,:,1) , 1);
val_R = nanmean( T1_mac(:,:,2) , 1);
% 
figure;
SurfStatViewData_HCP(val_L, surface_L, val_R, surface_R,'T1- uncorr',[0 0 0]) %inputs: data, surface, title, background colour
SurfStatColLim([950 1400]);
saveas(gcf,strcat(SavDir,SITE,'-SurfaceMap_T1uncorrected.png'))  


figure;
SurfStatViewData_HCP( (1./(val_L))*1000 , surface_L, (1./(val_R))*1000, surface_R,'R_1 (1/s)- uncorr',[0 0 0]) %inputs: data, surface, title, background colour
SurfStatColLim([1/1.4 1/0.95]);
saveas(gcf,strcat(SavDir,SITE,'-SurfaceMap_R1uncorrected.png'))  

val_L = nanmean( B1_mac(:,:,1) , 1);
val_R = nanmean( B1_mac(:,:,2) , 1);

figure;
SurfStatViewData_HCP(val_L, surface_L, val_R, surface_R,'B_1',[0 0 0]) %inputs: data, surface, title, background colour
SurfStatColLim([0.9 1.3]);
saveas(gcf,strcat(SavDir,SITE,'-SurfaceMap_B1.png'))  

% 
val_L = nanmean( T1_mac2(:,:,1) , 1);
val_R = nanmean( T1_mac2(:,:,2) , 1);

figure;
SurfStatViewData_HCP(val_L, surface_L, val_R, surface_R,'T1- corr',[0 0 0]) %inputs: data, surface, title, background colour
SurfStatColLim([950 1400]);
saveas(gcf,strcat(SavDir,SITE,'-SurfaceMap_T1corrected.png'))  

figure;
SurfStatViewData_HCP( (1./(val_L))*1000 , surface_L, (1./(val_R))*1000, surface_R,'R_1 (1/s) - corr',[0 0 0]) %inputs: data, surface, title, background colour
SurfStatColLim([1/1.4 1/0.95]);
saveas(gcf,strcat(SavDir,SITE,'-SurfaceMap_R1corrected.png'))  


%% Generate Surface Asymmetry.
R1_mac = 1./T1_mac;
R1_mac2 = 1./T1_mac2;

B1_asym_mac = (B1_mac(:,:,1) - B1_mac(:,:,2) ) ./ B1_mac(:,:,1);
R1_asym_mac = (R1_mac(:,:,1) - R1_mac(:,:,2) ) ./ R1_mac(:,:,1);
R1_asym_mac2 = (R1_mac2(:,:,1) - R1_mac2(:,:,2) ) ./ R1_mac2(:,:,1);

%% To clean it up, lets remove ROIs' that probably will have bad signal:
ROIs = [6, 14, 18,88, 93,103,106,109,104,110,118:122,126,127,131,153, 154,155,160,163, 164,166,167,168,172];
for i = 1:length(ROIs)
    label_L(label_L == ROIs(i) ) = 0;
end

%% Get ROI averages.
numSub = size(T1_mac,1);
numROIs = max(label_L); % get the number of ROIs to loop through 

ROI_B1_asym_mac = zeros(numSub,numROIs); % initialize matrix
ROI_T1_asym_mac = zeros(numSub,numROIs); % initialize matrix
ROI_T1_asym_mac2 = zeros(numSub,numROIs); % initialize matrix

for k = 1:numROIs  %for each of the labels

    mask_L = label_L == k;  %make a matrix of 0,1's where the desired label is

    for j = 1:numSub

        t1 = B1_asym_mac(j,:);
        t2 = R1_asym_mac(j,:); % Convert to R1
        t3 = R1_asym_mac2(j,:);  % Convert to R1
        
        ROI_B1_asym_mac(j,k)   = nanmean(t1(mask_L)); %%Calculates the ROI values for every subject in the vtk file
        ROI_T1_asym_mac(j,k) = nanmean( t2(mask_L)); %%Calculates the ROI values for every subject in the vtk file
        ROI_T1_asym_mac2(j,k) = nanmean( t3(mask_L)); %%Calculates the ROI values for every subject in the vtk file

    end
end





%% Now we values for a bunch of ROIs and Subjects

% Pool them all. 

x_Plot_B1_surf = ROI_B1_asym_mac(:);
y_Plot_R1_surf = ROI_T1_asym_mac(:);
y_Plot_R1_surf2 = ROI_T1_asym_mac2(:);

y_Plot_R1_surf( isnan(x_Plot_B1_surf) ) = [];y_Plot_R1_surf2( isnan(x_Plot_B1_surf) ) = [];  x_Plot_B1_surf( isnan(x_Plot_B1_surf) ) = [];
x_Plot_B1_surf( isnan(y_Plot_R1_surf) ) = []; y_Plot_R1_surf2( isnan(y_Plot_R1_surf) ) = [];y_Plot_R1_surf( isnan(y_Plot_R1_surf) ) = [];
x_Plot_B1_surf( isnan(y_Plot_R1_surf2) ) = []; y_Plot_R1_surf( isnan(y_Plot_R1_surf2) ) = [];y_Plot_R1_surf2( isnan(y_Plot_R1_surf2) ) = [];

y_Plot_R1_surf( isinf(x_Plot_B1_surf) ) = [];
y_Plot_R1_surf2( isinf(x_Plot_B1_surf) ) = [];
x_Plot_B1_surf( isinf(x_Plot_B1_surf) ) = [];

% y_Plot_R1_surf( x_Plot_B1_surf ==0 ) = [];
% y_Plot_R1_surf( x_Plot_B1_surf ==0 ) = [];
% x_Plot_B1_surf( x_Plot_B1_surf ==0 ) = [];

x_Plot_B1_surf( abs(y_Plot_R1_surf) >0.2 ) = [];
y_Plot_R1_surf2( abs(y_Plot_R1_surf) >0.2) = [];
y_Plot_R1_surf( abs(y_Plot_R1_surf) >0.2) = [];

% Plot
p1 = polyfit(x_Plot_B1_surf,y_Plot_R1_surf,1);
x1 = linspace(-0.3,0.3);
y1 = polyval(p1,x1);

figure;
heatscatter(x_Plot_B1_surf, y_Plot_R1_surf)
hold on
%plot( x1,y1, 'linewidth',2)
ylim([-0.25 0.25]); xlim([-0.25 0.25])
xlabel('L-R B_1 Asymmetry');
ylabel('L-R R_1 Asymmetry');
ax = gca; ax.FontSize = 20; 
hold off      
colorbar off
  set(gcf,'position',[10,400,500,400])     
hold off
saveas(gcf,strcat(SavDir,SITE,'-Asymmetry_b1vsR1uncorrected.png'))  
  


% corrected
p2 = polyfit(x_Plot_B1_surf,y_Plot_R1_surf2,1);
y2 = polyval(p2,x1);

figure;
heatscatter(x_Plot_B1_surf, y_Plot_R1_surf2)
hold on
%plot( x1,y2, 'linewidth',2)
ylim([-0.25 0.25]); xlim([-0.25 0.25])
xlabel('L-R B_1 Asymmetry');
ylabel('L-R R_1 Asymmetry');
ax = gca; ax.FontSize = 20; 
hold off      
colorbar off
  set(gcf,'position',[10,400,500,400])     
hold off
saveas(gcf,strcat(SavDir,SITE,'-Asymmetry_b1vsR1corrected.png'))  
     
%% Combine and plot
x_comb = vertcat(x_Plot_B1_surf, x_Plot_B1);
y_comb = vertcat(y_Plot_R1_surf, y_Plot_R1);


p = polyfit(x_comb,y_comb,1);
x1 = linspace(-0.2,0.3);
y1 = polyval(p,x1);



figure;
heatscatter(x_comb, y_comb)
hold on
plot(x1,y1,'linewidth',3)
plot(x1,y2,'linewidth',3)
legend






















